name: Node.js CICD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup node.js 
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: frontend compilation (syntax check)
        run: |
          cd client
          find . -name "*.js"  -exec node --check {} +  #what this comaand exactly do? can you explain in detail?
  # The above command is used to perform a syntax check on all JavaScript files in the "client"
  # directory and its subdirectories. Here's a breakdown of the command:
  # 1. `find . -name "*.js"`: This part of the command searches for all files with a ".js" extension starting 
  #from the current directory (denoted by ".") and its subdirectories. It will return a list of all JavaScript files found.
  # 2. `-exec node --check {} +`: This part of the command executes the `node --check` command on each of the files found by the `find` command.
  # The `{}` is a placeholder that represents each file found by the `find` command. The `+` at the end allows for multiple files to be 
  #processed in a single command, which can be more efficient than running the command separately for each file.
      - name: backend compilation (syntax check)
        run: |
          cd api
          find . -name "*.js"  -exec node --check {} + 
  gitleaks-scan:
        runs-on: Agent-1
        needs: compile
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: gitleaks setup
            uses: gitleaks/gitleaks-action@v2

          - name: Gitleaks Scan
            run: |
             gitleaks detect --source ./client --exit-code  1 
             gitleaks detect --source  ./api --exit-code  1
  trivy_fs_scan:
        runs-on: Agent-1
        needs: gitleaks-scan
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Run Trivy vulnerability scanner in fs mode
            uses: aquasecurity/trivy-action@v0.20.0
            with:
              scan-type: 'fs'
              scan-ref: '.'
              format: 'table'
              ignore-unfixed: true
              vuln_type: 'os,library'
              severity: 'CRITICAL,HIGH'
  sonar-frontend:
        runs-on: Agent-1
        needs: trivy_fs_scan
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: SonarCloud Scan for Frontend
            uses: sonarsource/sonarqube-scan-action@master
            with:
              projectBaseDir: client
              args: >
                -Dsonar.projectKey=myorg_client
                -Dsonar.projectName=myorg_client
                -Dsonar.sources=.
                -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  sonar-backend:
        runs-on: Agent-1  
        needs: sonar-frontend
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: SonarCloud Scan for Backend
            uses: sonarsource/sonarqube-scan-action@master
            with:
              projectBaseDir: api
              args: >
                -Dsonar.projectKey=myorg_api
                -Dsonar.projectName=myorg_api
                -Dsonar.sources=.
                -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  build_backend_docker_image_push:
        runs-on: ubuntu-latest
        needs: sonar-backend
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and push Docker image
            uses: docker/build-push-action@v6
            with:
               context: ./api
               push: true
               tags: lakshmipathiroyal/backend:latest
               file: ./api/Dockerfile
  build_frontend_docker_image_push:
        runs-on: ubuntu-latest
        needs: build_backend_docker_image_push
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and push Docker image
            uses: docker/build-push-action@v6
            with:
               context: ./client
               push: true
               tags: lakshmipathiroyal/frontend:latest
               file: ./client/Dockerfile
  trivy_image_scan:
        runs-on: Agent-1
        needs: build_frontend_docker_image_push
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Run Trivy vulnerability scanner in image mode for backend
            uses: aquasecurity/trivy-action@v0.20.0
            with:
              scan-type: 'image'
              image-ref: 'lakshmipathiroyal/backend:latest'
              format: 'table'
              exit-code: '0'
              ignore-unfixed: true
              vuln_type: 'os,library'
              severity: 'CRITICAL,HIGH'

          - name: Run Trivy vulnerability scanner in image mode for frontend
            uses: aquasecurity/trivy-action@v0.20.0
            with:
              scan-type: 'image'
              image-ref: 'lakshmipathiroyal/frontend:latest'
              format: 'table'
              ignore-unfixed: true
              vuln_type: 'os,library'
              severity: 'CRITICAL,HIGH'
  deploy_to_kubernetes:
        runs-on: Agent-1
        needs: trivy_image_scan
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: install aws cli
            run: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install --update
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-south-1
          - name: Set up kubectl
            uses: azure/setup-kubectl@v3  # why are we using azure setup kubectl action for setting up kubectl for AWS EKS cluster? can you explain in detail?
                                          # We are using the azure/setup-kubectl action to set up kubectl for our 
                                          #AWS EKS cluster because this action provides a convenient way to install and configure kubectl in our 
                                          #GitHub Actions workflow. The azure/setup-kubectl action is not limited to Azure Kubernetes Service (AKS)
                                          # and can be used to set up kubectl for any Kubernetes cluster, including AWS EKS. By using this action,
                                          # we can easily manage our Kubernetes deployments without having to manually install and configure kubectl in our workflow.
            with:
              version: 'latest'
          - name: configure kubeconfig for EKS cluster             #what is kubeconfig file and why do we need to configure it for EKS cluster? can you explain in detail?
                                                          # The kubeconfig file is a configuration file used by kubectl to access 
                                                          #and manage Kubernetes clusters. It contains information about the clusters, users, and contexts
                                                          # that kubectl can use to connect to different Kubernetes clusters. When we want to deploy our 
                                                          #application to an AWS EKS cluster, we need to configure the kubeconfig file with the necessary
                                                        # credentials and cluster information so that kubectl can authenticate and communicate with the 
                                                        #EKS cluster. This allows us to run kubectl commands to deploy our application, manage resources, 
                                                        #and perform other operations on the EKS cluster from our GitHub Actions workflow.
            run: |                                       # what is the below command doing? can you explain in detail?
              mkdir -p $HOME/.kube                                        # This command creates a directory named ".kube" in the home directory of the user running the GitHub Actions workflow. The "-p" flag ensures that the parent directories are created if they do not already exist.
              echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config   # This command takes the value of the KUBECONFIG secret, which is expected to be a string containing the contents of a kubeconfig file, and writes it to a file named "config" in the ".kube" directory created in the previous step. This effectively configures kubectl to use the provided kubeconfig for authentication and communication with the Kubernetes cluster.

          - name: Deploy to Kubernetes
            run: |
              kubectl apply -f k8s-prod/sc.yaml
              kubectl apply -f k8s-prod/mysql.yaml
              kubectl apply -f k8s-prod/backend.yaml
              kubectl apply -f k8s-prod/frontend.yaml
              kubectl apply -f k8s-prod/ingress.yaml
              kubectl apply -f k8s-prod/ci.yaml
          
